// FILE 27: SubtitleResponse.java
package com.eduplatform.video.dto;
import lombok.*;

@Data @NoArgsConstructor @AllArgsConstructor @Builder
public class SubtitleResponse {
    private String videoId;
    private String language;
    private String languageName;
    private String status;
    private String url;
    private Boolean isAutoGenerated;
}