package com.eduplatform.video.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;
import lombok.*;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document(collection = "video_subtitles")
public class VideoSubtitle {

    @Id
    private String id;

    @Indexed
    private String videoId;

    private String language; // en, hi, es, fr

    private String languageName; // English, Hindi

    private String subtitleUrl; // S3 URL to .vtt file

    @Indexed
    private String status; // UPLOADED, PROCESSING, READY, FAILED

    private Boolean isAutoGenerated;

    private Double accuracy; // For auto-generated (0-100)

    @Indexed
    private LocalDateTime uploadedAt;

    @Indexed
    private LocalDateTime createdAt;

    @Indexed
    private String tenantId;

    private Long version = 0L;
}