package com.eduplatform.admin.model;

public enum AuditAction {
    USER_CREATED,
    USER_UPDATED,
    USER_BANNED,
    USER_UNBANNED,
    USER_DELETED,
    COURSE_APPROVED,
    COURSE_REJECTED,
    COURSE_REMOVED,
    COURSE_PUBLISHED,
    COURSE_UNPUBLISHED,
    PAYMENT_REFUNDED,
    DISPUTE_RESOLVED,
    ADMIN_CREATED,
    ADMIN_DELETED,
    ADMIN_PERMISSIONS_CHANGED,
    CONTENT_REPORTED,
    REPORT_RESOLVED,
    SUBSCRIPTION_CANCELLED,
    USER_ROLE_CHANGED
}
